### ISSUE TITLE
Does not work on Thunderbird 78

### ISSUE THREAD

**Issue by nwhitehorn** [phavekes/unmangleOutlookSafelinks#18]
I think it needs the new "messageDisplayScripts" API (starting in Thunderbird 82) to work, so it's probably impossible to make it run in Thunderbird 7x and the shell parts will need to be rewritten for Thunderbird 8x+.

**Comment by nwhitehorn** [comment]
Similar addon for Thunderbird 78.4+:

https://addons.thunderbird.net/en-US/thunderbird/addon/safelink-removal/

**Comment by cschaffner** [comment]
> Similar addon for Thunderbird 78.4+:
> 
> https://addons.thunderbird.net/en-US/thunderbird/addon/safelink-removal/

I'm not sure this other add-on is doing the same, I can't get it to work...

**Comment by nwhitehorn** [comment]
I think it needs an update (I built from source), but it does work and is functioning for me as a full replacement.

**Comment by phavekes** [comment]
I'll put the update om my list... Please be patient ...

**Comment by phavekes** [comment]
Converting deprecated Legacy WebExtensions to MailExtensions is not simple :disappointed:

**Comment by phavekes** [comment]
It seems the necessary API's are not working until version 82+
https://thunderbird-webextensions.readthedocs.io/en/78/changes/beta82.html

**Comment by nwhitehorn** [comment]
They've been back-ported to 78.4 and onward.

**Comment by phavekes** [comment]
I've got a working version for TB82, I'll release a xpi for testing on github today.

**Comment by phavekes** [comment]
#19

**Comment by phavekes** [comment]
This xpi can be used for testing:
https://github.com/phavekes/unmangleOutlookSafelinks/raw/feature/TB78/unmangleOutlookSafelinks-3.0.0.xpi

**Comment by phavekes** [comment]
> They've been back-ported to 78.4 and onward.

I don't see messageDisplayScripts before version 82 : 
https://thunderbird-webextensions.readthedocs.io/en/78/changes/beta82.html#messagedisplayscripts-tabs

Where have you seen the backporting of this API?

**Comment by nwhitehorn** [comment]
Here: https://thunderbird-webextensions.readthedocs.io/en/78/messageDisplayScripts.html

**Comment by phavekes** [comment]
The update for version 78 (almost 90% rewrite) is published in the addon store now:
[Get it here](https://addons.thunderbird.net/nl/thunderbird/addon/unmangle-outlook-safelinks/)
Please submit any problems in a new issue here.
